app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

api_app:
    resource: "@AppBundle/Resources/config/api_routing.yml"
    prefix:   /


easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"