services:
#    app.example:
#        class: src\AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
   AppBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']
        autowire: true
